### ISSUE TITLE
regular expression matching in filter field seems to have problem

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/cloud-build-notifiers#81]
I was trying to use a regular expression match in the filter expression for an smtp-notifier but it causes a crash failure on deploy as seen in the screenshots 
![Screen Shot 2020-11-03 at 10 29 46 AM](https://user-images.githubusercontent.com/7189862/98006020-bce4c380-1dbf-11eb-921f-3acc1a9e4632.png)
![Screen Shot 2020-11-03 at 10 31 17 AM](https://user-images.githubusercontent.com/7189862/98006027-bfdfb400-1dbf-11eb-83d7-ae20cc24dc48.png)

**Comment by LOZORD** [comment]
I think the `match` part of your filter is incorrect -- I think you need to double-escape the back slashes like `\\d`. I was able to get it get a successful match test case with the following (I'll make a PR for the case shortly).

```golang
filter:    `build.status in [Build.Status.FAILURE, Build.Status.TIMEOUT] && build.substitutions["TAG_NAME"].matches("^v\\d{1}\\.\\d{1}\\.\\d{3}$")`
build:     &cbpb.Build{Status: cbpb.Build_TIMEOUT, Substitutions: map[string]string{"TAG_NAME": "v1.2.003"}},
```

**Comment by ggprod** [comment]
Thanks again @LOZORD !  Double backslashes solved the problem and it works as expected now.

**Comment by firezdog** [comment]
The fact that the strings need to be escaped in this way, and general handling of string literals in the yaml, should be documented.  Maybe everybody who uses yaml knows this, but I just spent quite a long time trying to apply the example

```
filter: <name> in build.tags
```

thinking i could either just insert the bare name i wanted into the example or else put quotes around it.  But the field fails to parse unless it is specified in this way:

```
filter: '"my_tag" in build.tags'
```

the documentation contains examples with string literals that are not enclosed like this, possibly because they do not occur at the start of the field?  this is non-obvious and needs to be documented.
